registration_app_created
Anton-bat/Workout_application pull request #1
Opened 2024-07-05 13:22 UTC by Anton-bat

Implemented fiatures:
- Added new templates: base, and for login and registration.
- Added a new class `RegisterView` for handling user registration.
- Added `login_view` and `logout_view` functions for handling authentication.

2024-07-05 17:18 UTC, vladysllav requested changes

2024-07-05 17:18 UTC, vladysllav commented on .vscode/settings.json
Цього на гіті бути не повинно

2024-07-05 17:18 UTC, vladysllav commented on workout_app/media/register.jpg
Медіа не можна заливати на гіт

2024-07-05 17:18 UTC, vladysllav commented on workout_app/workout_app/settings.py
> +        "NAME": "database_1",
Ці данні повинні бути в .env

2024-07-05 17:18 UTC, vladysllav commented on workout_app/workout_app/urls.py
> +    path("registration/", include("registration.urls")),
Краще назвати і модуль весь і юрл auth, бо там не тільки реєстрація

2024-07-17 13:13 UTC, Anton-bat commented on .vscode/settings.json
added workout_app/media, venv,. vscode to .gitignore
<img width="973" alt="Знімок екрана 2024-07-17 о 16 11 35" src="https://github.com/user-attachments/assets/5701ea7b-90b7-42a3-8088-227300e21500">

2024-07-17 13:35 UTC, Anton-bat commented on .vscode/settings.json
file .gitignore updated
<img width="837" alt="Знімок екрана 2024-07-17 о 16 34 35" src="https://github.com/user-attachments/assets/58f10efb-9461-43ed-ba2e-d7a6d85f9741">

2024-07-17 13:35 UTC, Anton-bat commented on workout_app/media/register.jpg
folder /workout_app/media/ added to .gitigrone
<img width="837" alt="Знімок екрана 2024-07-17 о 16 34 35" src="https://github.com/user-attachments/assets/9768fb0a-4db3-408d-8e03-e7545f73a3ad">

2024-07-17 13:37 UTC, Anton-bat commented on workout_app/workout_app/settings.py
> +        "NAME": "database_1",
file .env updated with following data.
<img width="882" alt="Знімок екрана 2024-07-17 о 16 37 10" src="https://github.com/user-attachments/assets/3d444276-78f8-4e87-985e-5f21701f30ad">

2024-07-17 13:40 UTC, Anton-bat commented on workout_app/workout_app/urls.py
> +    path("registration/", include("registration.urls")),
Тут я намагався змінити назву на auth, але постійно потім різноманітні помилки викидає, і не запускається сервер після цього. Чи можу поки залишити назву так як є?

2024-07-19 16:31 UTC, merged